# Generated by Django 4.1.7 on 2023-04-28 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_shippingaddress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
    ]
