# Generated by Django 4.1.7 on 2023-04-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_shippingaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
